import { RatioType } from './graphql';

export const origworld = {
  name: 'A Nice World 2',
  logo: 'icones/ecolo.jpg',
  money: 0,
  score: 0,
  totalangels: 0,
  activeangels: 0,
  angelbonus: 2,
  lastupdate: 0,
  products: [
    {
      id: 1,
      name: 'Paper Bags',
      logo: 'icones/sacpapier.jpg',
      cout: 4,
      croissance: 1.07,
      revenu: 1,
      vitesse: 500,
      quantite: 1,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        {
          name: 'Paper is beautiful !',
          logo: 'icones/sacpapier.jpg',
          seuil: 20,
          idcible: 1,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
        {
          name: "Don't forget your paper bag  !",
          logo: 'icones/sacpapier.jpg',
          seuil: 75,
          idcible: 1,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
      ],
    },
    {
      id: 2,
      name: 'Recycle Bins',
      logo: 'icones/recyclage.jpg',
      cout: 60,
      croissance: 1.15,
      revenu: 60,
      vitesse: 3000,
      quantite: 0,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        {
          name: 'Give me some good bins !',
          logo: 'icones/recyclage.jpg',
          seuil: 20,
          idcible: 2,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
        {
          name: 'My Trashcans are better than yours ! ',
          logo: 'icones/recyclage.jpg',
          seuil: 75,
          idcible: 2,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
      ],
    },
  ],
  allunlocks: [
    {
      name: 'All is better than one',
      logo: 'icones/all.jpg',
      seuil: 30,
      idcible: 0,
      ratio: 2,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'To take and not to give',
      logo: 'icones/all.jpg',
      seuil: 150,
      idcible: 0,
      ratio: 3,
      typeratio: RatioType.gain,
      unlocked: false,
    },
  ],
  upgrades: [
    {
      name: 'Do you like paper bag ?',
      logo: 'icones/sacpapier.jpg',
      seuil: 1000,
      idcible: 1,
      ratio: 3,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'This is my bin',
      logo: 'icones/recyclage.jpg',
      seuil: 15000,
      idcible: 2,
      ratio: 3,
      typeratio: RatioType.gain,
      unlocked: false,
    },
  ],
  angelupgrades: [
    {
      name: 'Angel Sacrifice',
      logo: 'icones/angel.png',
      seuil: 10,
      idcible: 0,
      ratio: 3,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Angelic Mutiny',
      logo: 'icones/angel.png',
      seuil: 100000,
      idcible: -1,
      ratio: 2,
      typeratio: RatioType.ange,
      unlocked: false,
    },
  ],
  managers: [
    {
      name: 'Wangari Maathai',
      logo: 'icones/WangariMaathai.jpg',
      seuil: 10,
      idcible: 1,
      ratio: 0,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Ellen MacArthur',
      logo: 'icones/ellenmacarthur.jpg',
      seuil: 15000,
      idcible: 2,
      ratio: 0,
      typeratio: RatioType.gain,
      unlocked: false,
    },
  ],
};